[username]
format = '[$user]($style)'
style_root = 'red bold'
style_user = 'green bold'

[hostname]
format = '@[$hostname]($style) '
style = 'blue dimmed bold'

[directory]
style = 'bold white'

[git_branch]
style = 'bold yellow'
[git_status]
conflicted = 'C'
modified = 'M'
renamed = 'R'
staged = 'S'
untracked = 'U'
disabled = true

[gcloud]
disabled = true
[golang]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
